name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["Backlog: bug report"]
projects: ["inno-swp-2025/1"]
body:
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Keep the comment.
        Follow the instructions in the comment.
        Write your text after the comment.
      placeholder: |
        <!--
        Explain step by step how to reproduce the behavior.
        Provide screenshots or a video if necessary.

        Example:

        1. On a test device, clear all app data or perform a fresh install to simulate a first-time user.
        1. Open the app. Do not log in or create an account.
        1. Remain on the initial "For You" feed that autoplays.
        1. Swipe up to view the next video for the first 10-15 videos.
        -->
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: |
        Keep the comment.
        Follow the instructions in the comment.
        Write your text after the comment.
      placeholder: |
        <!--
        Briefly describe what you expect to happen.

        Example:

        Within the first 10 videos, a new user should see content from a variety of popular categories (e.g., comedy, dance, animals, DIY, educational).
        The feed should feel diverse, aligning with AC-2 of #9.
        -->
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Actual Behavior
      description: |
        Keep the comment.
        Follow the instructions in the comment.
        Write your text after the comment.
      placeholder: |
        <!--
        Briefly describe what you're experiencing.

        Example:

        The initial feed is almost entirely composed of videos from a single category.
        After swiping through 10 videos, approximately 8-9 of them were dance-related challenges, providing a monotonous and non-diverse first-time user experience.
        -->
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: "<h2> Tasks </h2>"
      description: |
        Don't change the text in this field!
      value: |
        Sub-issues are tasks that resolve this bug.
    validations:
      required: false
