name: Bug Report for the web app.
description: File a bug report for the web app.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["inno-swp-2025/1"]
assignees:
  - deemp
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    attributes:
      label: Current Behavior
      description: Briefly describe what you're experiencing.
      placeholder: I experience a bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Briefly describe what you expect to happen.
      placeholder: I expect no bug.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Explain step by step how to reproduce the behavior. 

        Provide screenshots or a video if necessary.
      placeholder: |
        1. In this environment ...
        1. With this config ...
        1. With this app version ...
        1. Run '...'
        1. See error...
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    attributes:
      label: Your OS
      description: |
        Example:
        
        OS: Ubuntu 24.04
      value: |
        OS:
      render: markdown
    validations:
      required: true
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Relevant acceptance criteria
      description: Please specify or link relevant acceptance criteria so that developers can check after fixing this bug that their fixes didn't break anything.
      placeholder: Listen to your heart.
      value: "Listen to your heart."
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false