name: "Task"
description: "Create a task."
title: "[Task]: "
labels: ["Task: development"]
projects: ["inno-swp-2025/2"]
body:
  - type: textarea
    id: about-tasks
    attributes:
      label: "<!-- About tasks -->"
      description: |
        Don't change the text in this field!
        Follow the instructions in the comment.
      value: |
        <!--
        This form is for creating a specific, actionable task.
        Tasks should be small enough to be completed by one person in a short amount of time.
        Each task must be a sub-issue of a Product Backlog Item issue.
        -->
    validations:
      required: false

  - type: textarea
    id: task-description-and-context
    attributes:
      label: "<h2> Task Description & Context </h2>"
      description: |
        Keep the comment.
        Follow the instructions in the comment.
        Write your text after the comment.
      value: |
        <!--
        Briefly describe what this task is for.
        Explain its role in the parent user story and what specific part of the functionality it covers.

        Example:

        Create the backend API endpoint for liking a video.
        The endpoint will handle authentication, database updates, and return the correct response codes.
        -->
    validations:
      required: true

  - type: textarea
    id: implementation-steps
    attributes:
      label: "<h2> Implementation Steps </h2>"
      description: |
        Keep the comment.
        Follow the instructions in the comment.
        Write your text after the comment.
      value: |
        <!--
        Break down the task into a checklist of specific, technical steps.
        This is your "how-to" guide for meeting the Task Acceptance Criteria.
        Think about files to modify, functions to create, tests to write, configurations to change, and corner cases to handle.

        Example:

        - [ ] Create the POST /api/v1/video/{id}/like route and its controller function.
        - [ ] Implement the LikeService logic to handle successful like/unlike operations, 404 (video not found), and 409 (already liked) responses.
        - [ ] Apply JWT authentication middleware to the new like route to ensure it's protected.
        - [ ] Write unit tests for LikeService covering all scenarios and document the new endpoint in the OpenAPI/Swagger spec.
        -->
    validations:
      required: false

  - type: textarea
    id: task-acceptance-criteria
    attributes:
      label: "<h2> Task Acceptance Criteria </h2>"
      description: |
        Keep the comment.
        Follow the instructions in the comment.
        Write your text after the comment.
      value: |
        <!--
        List specific, verifiable, and technical outcomes.
        This is what will be checked during code review.

        Example:

        - [ ] A `POST` route is created at `/api/v1/video/{id}/like`.
        - [ ] The route is protected and requires a valid JWT.
        - [ ] A successful request returns a `200 OK` status.
        - [ ] A request for a video the user has already liked returns a `409 Conflict`.
        - [ ] A request with a non-existent `video_id` returns a `404 Not Found`.
        - [ ] Unit tests for the `LikeService` are written and pass with >90% coverage.
        - [ ] The new endpoint is documented in the OpenAPI/Swagger spec.
        -->
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: "<h2> Blockers </h2>"
      description: |
        Don't change the text in this field!
      value: |
        Sub-issues are blockers for this task.
    validations:
      required: false
