name: "User Story"
description: "File a user story for a new feature or improvement."
title: "[User Story]: "
labels: ["PBI: user story"]
projects: ["inno-swp-2025/1"]
body:
  - type: textarea
    id: user-story-sentence
    attributes:
      label: <h2> User Story </h2>
      description: |
        Keep the comment.
        Follow the instructions in the comment.
        Write your text after the comment.
      value: |
        <!--
        Write the full user story in a single sentence following the format:

        As a [persona],
        I want to [action]
        so that [outcome].

        Example:

        As a content creator,
        I want to apply visual effects and filters
        so that I can make my content more creative and stand out.
        -->
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "<h2> Acceptance criteria (AC) </h2>"
      description: |
        Keep the comment.
        Follow the instructions in the comment.
        Write your text after the comment.
      value: |
        <!--
        Define the specific, testable (pass-fail) scenarios that must be met for this story to be complete.
        Each criterion should be in its own section below.
        Use the GIVEN/WHEN/THEN/AND/BUT format for clarity.

        Add or remove "AC" sections as necessary.
        -->
    validations:
      required: false

  - type: textarea
    id: acceptance-criterion-1
    attributes:
      label: "AC-1"
      placeholder: |
        GIVEN a user is viewing a video's comment section
        WHEN the user types a comment containing a banned word and hits "Send"
        THEN an error message "This comment violates our community guidelines" is displayed
        BUT the comment does not appear in the comment list
        AND the comment count on the video does not increase
    validations:
      required: true

  - type: textarea
    id: acceptance-criterion-2
    attributes:
      label: "AC-2"
      placeholder: |
        GIVEN ...
        WHEN ...
        THEN ...
    validations:
      required: false

  - type: textarea
    id: acceptance-criterion-3
    attributes:
      label: "AC-3"
      placeholder: |
        GIVEN ...
        WHEN ...
        THEN ...
    validations:
      required: false

  - type: textarea
    id: tasks
    attributes:
      label: "<h2> Tasks </h2>"
      description: |
        Don't change the text in this field!
      value: |
        Sub-issues are tasks that implement this user story.
    validations:
      required: false
